/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DisastersRouteImport } from './routes/disasters'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminAuthRouteImport } from './routes/admin-auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AdminAuthIndexRouteImport } from './routes/admin-auth.index'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AdminAuthSignupRouteImport } from './routes/admin-auth.signup'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedRequestRouteImport } from './routes/_authenticated/request'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDonateRouteImport } from './routes/_authenticated/donate'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin.users'
import { Route as AuthenticatedAdminAdminTransactionsRouteImport } from './routes/_authenticated/_admin/admin.transactions'
import { Route as AuthenticatedAdminAdminRequestsRouteImport } from './routes/_authenticated/_admin/admin.requests'
import { Route as AuthenticatedAdminAdminOperationsRouteImport } from './routes/_authenticated/_admin/admin.operations'
import { Route as AuthenticatedAdminAdminDonationsRouteImport } from './routes/_authenticated/_admin/admin.donations'
import { Route as AuthenticatedAdminAdminDisastersRouteImport } from './routes/_authenticated/_admin/admin.disasters'
import { Route as AuthenticatedAdminAdminAllocationsRouteImport } from './routes/_authenticated/_admin/admin.allocations'

const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DisastersRoute = DisastersRouteImport.update({
  id: '/disasters',
  path: '/disasters',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin-auth',
  path: '/admin-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AdminAuthIndexRoute = AdminAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AdminAuthSignupRoute = AdminAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestRoute = AuthenticatedRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDonateRoute = AuthenticatedDonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminTransactionsRoute =
  AuthenticatedAdminAdminTransactionsRouteImport.update({
    id: '/admin/transactions',
    path: '/admin/transactions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminRequestsRoute =
  AuthenticatedAdminAdminRequestsRouteImport.update({
    id: '/admin/requests',
    path: '/admin/requests',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminOperationsRoute =
  AuthenticatedAdminAdminOperationsRouteImport.update({
    id: '/admin/operations',
    path: '/admin/operations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminDonationsRoute =
  AuthenticatedAdminAdminDonationsRouteImport.update({
    id: '/admin/donations',
    path: '/admin/donations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminDisastersRoute =
  AuthenticatedAdminAdminDisastersRouteImport.update({
    id: '/admin/disasters',
    path: '/admin/disasters',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminAllocationsRoute =
  AuthenticatedAdminAdminAllocationsRouteImport.update({
    id: '/admin/allocations',
    path: '/admin/allocations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-auth': typeof AdminAuthRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/disasters': typeof DisastersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/transparency': typeof TransparencyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/donate': typeof AuthenticatedDonateRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/request': typeof AuthenticatedRequestRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/admin-auth/signup': typeof AdminAuthSignupRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin-auth/': typeof AdminAuthIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/allocations': typeof AuthenticatedAdminAdminAllocationsRoute
  '/admin/disasters': typeof AuthenticatedAdminAdminDisastersRoute
  '/admin/donations': typeof AuthenticatedAdminAdminDonationsRoute
  '/admin/operations': typeof AuthenticatedAdminAdminOperationsRoute
  '/admin/requests': typeof AuthenticatedAdminAdminRequestsRoute
  '/admin/transactions': typeof AuthenticatedAdminAdminTransactionsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disasters': typeof DisastersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/transparency': typeof TransparencyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/donate': typeof AuthenticatedDonateRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/request': typeof AuthenticatedRequestRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/admin-auth/signup': typeof AdminAuthSignupRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin-auth': typeof AdminAuthIndexRoute
  '/auth': typeof AuthIndexRoute
  '/admin/allocations': typeof AuthenticatedAdminAdminAllocationsRoute
  '/admin/disasters': typeof AuthenticatedAdminAdminDisastersRoute
  '/admin/donations': typeof AuthenticatedAdminAdminDonationsRoute
  '/admin/operations': typeof AuthenticatedAdminAdminOperationsRoute
  '/admin/requests': typeof AuthenticatedAdminAdminRequestsRoute
  '/admin/transactions': typeof AuthenticatedAdminAdminTransactionsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-auth': typeof AdminAuthRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/disasters': typeof DisastersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/transparency': typeof TransparencyRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/donate': typeof AuthenticatedDonateRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/request': typeof AuthenticatedRequestRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/admin-auth/signup': typeof AdminAuthSignupRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin-auth/': typeof AdminAuthIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/_admin/admin/allocations': typeof AuthenticatedAdminAdminAllocationsRoute
  '/_authenticated/_admin/admin/disasters': typeof AuthenticatedAdminAdminDisastersRoute
  '/_authenticated/_admin/admin/donations': typeof AuthenticatedAdminAdminDonationsRoute
  '/_authenticated/_admin/admin/operations': typeof AuthenticatedAdminAdminOperationsRoute
  '/_authenticated/_admin/admin/requests': typeof AuthenticatedAdminAdminRequestsRoute
  '/_authenticated/_admin/admin/transactions': typeof AuthenticatedAdminAdminTransactionsRoute
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-auth'
    | '/auth'
    | '/contact'
    | '/disasters'
    | '/reset-password'
    | '/transparency'
    | '/dashboard'
    | '/donate'
    | '/profile'
    | '/request'
    | '/requests'
    | '/transactions'
    | '/admin-auth/signup'
    | '/auth/forgot'
    | '/auth/signup'
    | '/admin-auth/'
    | '/auth/'
    | '/admin/allocations'
    | '/admin/disasters'
    | '/admin/donations'
    | '/admin/operations'
    | '/admin/requests'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/disasters'
    | '/reset-password'
    | '/transparency'
    | '/dashboard'
    | '/donate'
    | '/profile'
    | '/request'
    | '/requests'
    | '/transactions'
    | '/admin-auth/signup'
    | '/auth/forgot'
    | '/auth/signup'
    | '/admin-auth'
    | '/auth'
    | '/admin/allocations'
    | '/admin/disasters'
    | '/admin/donations'
    | '/admin/operations'
    | '/admin/requests'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin-auth'
    | '/auth'
    | '/contact'
    | '/disasters'
    | '/reset-password'
    | '/transparency'
    | '/_authenticated/_admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/donate'
    | '/_authenticated/profile'
    | '/_authenticated/request'
    | '/_authenticated/requests'
    | '/_authenticated/transactions'
    | '/admin-auth/signup'
    | '/auth/forgot'
    | '/auth/signup'
    | '/admin-auth/'
    | '/auth/'
    | '/_authenticated/_admin/admin/allocations'
    | '/_authenticated/_admin/admin/disasters'
    | '/_authenticated/_admin/admin/donations'
    | '/_authenticated/_admin/admin/operations'
    | '/_authenticated/_admin/admin/requests'
    | '/_authenticated/_admin/admin/transactions'
    | '/_authenticated/_admin/admin/users'
    | '/_authenticated/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminAuthRoute: typeof AdminAuthRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  DisastersRoute: typeof DisastersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TransparencyRoute: typeof TransparencyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disasters': {
      id: '/disasters'
      path: '/disasters'
      fullPath: '/disasters'
      preLoaderRoute: typeof DisastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-auth': {
      id: '/admin-auth'
      path: '/admin-auth'
      fullPath: '/admin-auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin-auth/': {
      id: '/admin-auth/'
      path: '/'
      fullPath: '/admin-auth/'
      preLoaderRoute: typeof AdminAuthIndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin-auth/signup': {
      id: '/admin-auth/signup'
      path: '/signup'
      fullPath: '/admin-auth/signup'
      preLoaderRoute: typeof AdminAuthSignupRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/request': {
      id: '/_authenticated/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof AuthenticatedRequestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donate': {
      id: '/_authenticated/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof AuthenticatedDonateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/transactions': {
      id: '/_authenticated/_admin/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AuthenticatedAdminAdminTransactionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/requests': {
      id: '/_authenticated/_admin/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/operations': {
      id: '/_authenticated/_admin/admin/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AuthenticatedAdminAdminOperationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/donations': {
      id: '/_authenticated/_admin/admin/donations'
      path: '/admin/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AuthenticatedAdminAdminDonationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/disasters': {
      id: '/_authenticated/_admin/admin/disasters'
      path: '/admin/disasters'
      fullPath: '/admin/disasters'
      preLoaderRoute: typeof AuthenticatedAdminAdminDisastersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/allocations': {
      id: '/_authenticated/_admin/admin/allocations'
      path: '/admin/allocations'
      fullPath: '/admin/allocations'
      preLoaderRoute: typeof AuthenticatedAdminAdminAllocationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminAllocationsRoute: typeof AuthenticatedAdminAdminAllocationsRoute
  AuthenticatedAdminAdminDisastersRoute: typeof AuthenticatedAdminAdminDisastersRoute
  AuthenticatedAdminAdminDonationsRoute: typeof AuthenticatedAdminAdminDonationsRoute
  AuthenticatedAdminAdminOperationsRoute: typeof AuthenticatedAdminAdminOperationsRoute
  AuthenticatedAdminAdminRequestsRoute: typeof AuthenticatedAdminAdminRequestsRoute
  AuthenticatedAdminAdminTransactionsRoute: typeof AuthenticatedAdminAdminTransactionsRoute
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminAllocationsRoute:
      AuthenticatedAdminAdminAllocationsRoute,
    AuthenticatedAdminAdminDisastersRoute:
      AuthenticatedAdminAdminDisastersRoute,
    AuthenticatedAdminAdminDonationsRoute:
      AuthenticatedAdminAdminDonationsRoute,
    AuthenticatedAdminAdminOperationsRoute:
      AuthenticatedAdminAdminOperationsRoute,
    AuthenticatedAdminAdminRequestsRoute: AuthenticatedAdminAdminRequestsRoute,
    AuthenticatedAdminAdminTransactionsRoute:
      AuthenticatedAdminAdminTransactionsRoute,
    AuthenticatedAdminAdminUsersRoute: AuthenticatedAdminAdminUsersRoute,
    AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDonateRoute: typeof AuthenticatedDonateRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRequestRoute: typeof AuthenticatedRequestRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDonateRoute: AuthenticatedDonateRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRequestRoute: AuthenticatedRequestRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminAuthRouteChildren {
  AdminAuthSignupRoute: typeof AdminAuthSignupRoute
  AdminAuthIndexRoute: typeof AdminAuthIndexRoute
}

const AdminAuthRouteChildren: AdminAuthRouteChildren = {
  AdminAuthSignupRoute: AdminAuthSignupRoute,
  AdminAuthIndexRoute: AdminAuthIndexRoute,
}

const AdminAuthRouteWithChildren = AdminAuthRoute._addFileChildren(
  AdminAuthRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminAuthRoute: AdminAuthRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  DisastersRoute: DisastersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TransparencyRoute: TransparencyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
